### ISSUE TITLE
스크립트 파일 하나로 합치기

### ISSUE THREAD

**Issue by MaetDol** [MaetDol/tasker-house-holder#1]
너무 짧은 내용의 스크립트들이 분산되어 있어 여러 파일을 돌아다녀야합니다.
하나의 파일로 합치고 정확한 구분이 필요하다면 함수로 묶는 방안을 생각해봐야합니다.

**Comment by MaetDol** [comment]
테스커에서 테스크를 분할해놓았는데 여기서 사용되는 각 스크립트마다 분할해둬서 이런 문제가 생긴 것 같아요
불필요한 테스크를 합치고, 스크립트단에서 처리할 수 있다면 스크립트단으로 옮기는게 관리하기 좋을 것 같습니다.

**Comment by MaetDol** [comment]
일부 스크립트로 대체 불가능한 Task(Notify 에서 특정 Action을 지정해줄 수 없음)가 있고, 다른 Task를 호출하면서 매개변수로 넘겨 줄 때 제한이 있어서 각 Task에서 특정 함수(Splitter)를 호출해야하는 경우가 있음

**Comment by FEhyoeun** [comment]
그렇구나.. 몰랐네

**Comment by MaetDol** [comment]
이젠 안다!

**Comment by MaetDol** [comment]
지금 상황이면 어느정도 모였다구 생각합니다!
때문에 해당 티켓은 close 할게요~
